protocol git
action launch --type=tab --title "$FRAGMENT $FILE_PATH" --cwd $FILE_PATH lazygit

protocol kitty
path /launch/tab
action launch --type=tab $SHELL

protocol kitty
path /launch/nix-rebuild
fragment_matches (switch)
action launch --type=tab --title 'nix-rebuild $FRAGMENT' $SHELL -c 'nix-rebuild $FRAGMENT || read -p "echo Press enter to continue"'

protocol kitty
path /launch/nix
fragment_matches (nix-sync)
action launch --type=tab --title $FRAGMENT $SHELL -c '$FRAGMENT || read -p "echo Press enter to continue"'

protocol kitty
path /launch/lazygit
action launch --type=tab --title lazygit $SHELL -c 'lazygit --use-config-file $HOME/nix/desktop/programs/terminals/kitty/launch-lazygit.yaml'

protocol kitty
path /launch/k9s
fragment_matches (|readonly)
action launch --type=tab --title k9s $SHELL -c 'k9s --readonly --command context'

protocol kitty
path /launch/zai
action launch --type=tab --title zai $SHELL -c 'cd $HOME/zai && uv run fastapi dev zai'

protocol kitty
path /launch/cookie
fragment_matches cookie-(login)
action launch --type=tab --title $FRAGMENT $SHELL -c '$FRAGMENT'
