# https://github.com/nikitabobko/AeroSpace
# https://nikitabobko.github.io/AeroSpace/guide

# [default]
start-at-login = true
after-login-command = []
after-startup-command = []
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
accordion-padding = 32
default-root-container-layout = "tiles"
default-root-container-orientation = "auto"
on-focused-monitor-changed = []
automatically-unhide-macos-hidden-apps = false

[key-mapping]
preset = "qwerty"

[gaps]
inner.horizontal = 4
inner.vertical = 4
outer.left = 4
outer.bottom = 4
outer.top = 4
outer.right = 4

[mode.main.binding]
# All possible keys:
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# All possible modifiers: cmd, alt, ctrl, shift
# All possible commands: https://nikitabobko.github.io/AeroSpace/commands

# default keys
## hyper
cmd-ctrl-alt-shift-left = "focus left --boundaries all-monitors-outer-frame"
cmd-ctrl-alt-shift-right = "focus right --boundaries all-monitors-outer-frame"
cmd-ctrl-alt-shift-up = "focus up --boundaries all-monitors-outer-frame"
cmd-ctrl-alt-shift-down = "focus down --boundaries all-monitors-outer-frame"
cmd-ctrl-alt-shift-enter = "fullscreen"
## hyper-fn
cmd-ctrl-alt-shift-home = "move left --boundaries all-monitors-outer-frame"
cmd-ctrl-alt-shift-pageUp = "move up --boundaries all-monitors-outer-frame"
cmd-ctrl-alt-shift-pageDown = "move down --boundaries all-monitors-outer-frame"
cmd-ctrl-alt-shift-end = "move right --boundaries all-monitors-outer-frame"
## hyper-alt
cmd-ctrl-shift-leftSquareBracket = "layout tiles"
cmd-ctrl-shift-rightSquareBracket = "layout accordion"
cmd-ctrl-shift-semicolon = "layout tiles horizontal"
cmd-ctrl-shift-quote = "layout tiles vertical"
cmd-ctrl-shift-minus = "resize smart -64"
cmd-ctrl-shift-equal = "resize smart +64"
cmd-ctrl-shift-slash = "mode service"
cmd-ctrl-shift-enter = "flatten-workspace-tree"
# cmd-ctrl-shift-backspace = "enable toggle" # defined at `keyboard.yaml` file

# workspace
## hyper
cmd-ctrl-alt-shift-1 = "workspace 1"
cmd-ctrl-alt-shift-2 = "workspace 2"
cmd-ctrl-alt-shift-3 = "workspace 3"
cmd-ctrl-alt-shift-4 = "workspace 4"
cmd-ctrl-alt-shift-5 = "workspace 5"
cmd-ctrl-alt-shift-6 = "workspace 6"
cmd-ctrl-alt-shift-7 = "workspace 7"
cmd-ctrl-alt-shift-8 = "workspace 8"
cmd-ctrl-alt-shift-9 = "workspace 9"
## hyper-alt
cmd-ctrl-shift-1 = "move-node-to-workspace 1"
cmd-ctrl-shift-2 = "move-node-to-workspace 2"
cmd-ctrl-shift-3 = "move-node-to-workspace 3"
cmd-ctrl-shift-4 = "move-node-to-workspace 4"
cmd-ctrl-shift-5 = "move-node-to-workspace 5"
cmd-ctrl-shift-6 = "move-node-to-workspace 6"
cmd-ctrl-shift-7 = "move-node-to-workspace 7"
cmd-ctrl-shift-8 = "move-node-to-workspace 8"
cmd-ctrl-shift-9 = "move-node-to-workspace 9"
cmd-ctrl-shift-left = "workspace prev"
cmd-ctrl-shift-right = "workspace next"
## hyper-alt-fn
cmd-ctrl-shift-home = "move-node-to-workspace prev --focus-follows-window"
cmd-ctrl-shift-end = "move-node-to-workspace next --focus-follows-window"

[mode.service.binding]
esc = ["reload-config", "mode main"]
r = ["flatten-workspace-tree", "mode main"]
backspace = ["close-all-windows-but-current", "mode main"]

[[on-window-detected]]
if.app-id = 'com.DanPristupov.Fork'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.riotgames.RiotGames.RiotClient'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.riotgames.LeagueofLegends.LeagueClient'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.riotgames.LeagueofLegends.LeagueClientUx'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.riotgames.LeagueofLegends.GameClient'
run = ['layout floating']
