{ platform, ... }:
if platform == "darwin" then
  {
    homebrew = {
      taps = [
        "cockroachdb/tap"
        "common-fate/granted"
        "lingrino/tap"
        "nikitabobko/tap"
      ];
      brews = [
        "azure-cli"
        "cloudflared"
        "cockroach-sql"
        "codex"
        "docker-credential-helper"
        "git-grab"
        "granted"
        "incus"
        "kubetail"
        "libmagic"
        "lume"
        "mas"
        "ruby-build"
        "sqlcipher" # macOS's python3-sqlcipher uses brew's sqlcipher
        "vaku"
      ];
      casks = [
        "1password"
        "aerospace"
        "aldente"
        "balenaetcher"
        "betterdisplay"
        "chatgpt"
        "claude"
        "claude-code"
        "cloudflare-warp"
        "codeql"
        "container"
        "db-browser-for-sqlite"
        "deepl"
        "devtoys"
        "firefox"
        "font-jetbrains-mono"
        "font-sf-mono"
        "font-sf-pro"
        "fork"
        "gcloud-cli"
        "ghostty"
        "github"
        "google-chrome"
        "google-drive"
        "jetbrains-toolbox"
        "jordanbaird-ice"
        "karabiner-elements"
        "kdiff3"
        "keka"
        "latest"
        "linearmouse"
        "little-snitch"
        "micro-snitch"
        "numi"
        "obsidian"
        "ollama-app"
        "orbstack"
        "osquery"
        "privileges"
        "raycast"
        "ridibooks"
        "secretive"
        "sf-symbols"
        "slack"
        "slack-cli"
        "tailscale-app"
        "teleport-suite"
        "typora"
        "visual-studio-code"
        "wireshark-app"
        "wooshy"
        "zed"
        "zen"
      ];
    };
  }
else
  { }
