{ pkgs, ... }:
{
  home.packages =
    (with pkgs; [
      asciinema
      awscli2
      axel
      b3sum
      bkt
      btop
      capstone
      cmctl
      cosign
      cri-tools
      d2
      devbox
      dnscrypt-proxy
      docker
      docker-client
      dog
      duf
      eclint
      entr
      exif
      eza
      fclones
      fq
      fswatch
      func
      git
      git-absorb
      git-branchless
      git-filter-repo
      git-secrets
      git-standup
      git-town
      gnupg
      graphviz
      htop
      igrep
      imagemagick
      iperf3
      jo
      jsonnet
      jwt-cli
      kubeswitch
      lima
      lnav
      lz4
      lzop
      mariadb
      mariadb-client
      markscribe # charmbracelet
      mdformat
      minicom
      mitmproxy
      nil
      nix-prefetch-scripts
      nixd
      nixfmt-rfc-style
      nixpacks
      nmap
      oha
      openssl
      p7zip
      pdfgrep
      pgcli
      pinentry_mac
      postgresql
      procs
      pv
      pyp
      q
      rage
      reflex
      ripgrep-all
      rq
      rsync
      rustc
      rustpython
      s5cmd
      safe-rm
      saml2aws
      skopeo
      socat
      spice-gtk
      sqlcipher
      sqlite-utils
      sqlite-web
      ssm-session-manager-plugin
      tailspin
      terminal-notifier
      tig
      tldr
      tomlq
      treefmt
      trippy
      wabt
      wgcf
      wireguard-go
      wireguard-tools
      xonsh
      xxh
      xxHash
      xz
      yubico-piv-tool
      yubikey-manager
      zstd
    ])
    ++ (with pkgs.nur.repos.charmbracelet; [
      charm
      confettysh
      crush
      freeze
      glow
      gum
      # markscribe
      melt
      mods
      pop
      sequin
      skate
      soft-serve
      vhs
      wishlist
    ]);
}
